# rust-toolchain.toml - Toolchain overrides file
# This file declares the Rust toolchain used by the project.
# Documentation: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "nightly-2025-11-15" # "stable"
components = ["rust-analyzer"]
